use_frameworks!

target 'OculusReparo_Example' do
  pod 'OculusReparo', :path => '../'

  target 'OculusReparo_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0'
  pod 'Nimble', '~> 5.0'
  end
end
