use_frameworks!

target 'OculusReparo_Example' do
  pod 'OculusReparo', :path => '../'

  target 'OculusReparo_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
